version: "3"

services:
    web:
        image: nginx:latest
        ports:
            - "8000:80"
        volumes:
            - ./:/app
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf

    php:
        image: php:7-fpm
        volumes:
            - .:/app
